import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignInButton,
  UserButton,
} from "@clerk/nextjs";

import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <div>
              <ul className="flex justify-between m-10 items-center">
                <div>
                  <Link href="/">
                    <li>Home</li>
                  </Link>
                </div>
                <div className="flex gap-10">
                  <div>
                    <ul>
                      <li>
                        <SignedIn>
                          <UserButton showName />
                        </SignedIn>
                      </li>
                      <li>
                        <SignedOut>
                          <div>
                            <SignInButton>
                              <button className="btn btn-primary">
                                Sign in
                              </button>
                            </SignInButton>
                          </div>
                        </SignedOut>
                      </li>
                    </ul>
                  </div>
                </div>
              </ul>
            </div>
          </header>
          {children}
        </body>
      </html>
    </ClerkProvider>
  );
}
